2024-06-15 10:29:49 | INFO | model_worker | args: Namespace(host='localhost', port=31002, worker_address='http://localhost:31002', controller_address='http://localhost:31001', model_path='/home/c205/workspace/models/Apollo-7B/', revision='main', device='cuda', gpus=None, num_gpus=1, max_gpu_memory=None, dtype=None, load_8bit=False, cpu_offloading=False, gptq_ckpt=None, gptq_wbits=16, gptq_groupsize=-1, gptq_act_order=False, awq_ckpt=None, awq_wbits=16, awq_groupsize=-1, enable_exllama=False, exllama_max_seq_len=4096, exllama_gpu_split=None, exllama_cache_8bit=False, enable_xft=False, xft_max_seq_len=4096, xft_dtype=None, model_names=None, conv_template=None, embed_in_truncate=False, limit_worker_concurrency=5, stream_interval=2, no_register=False, seed=None, debug=False, ssl=False)
2024-06-15 10:29:49 | INFO | model_worker | Loading the model ['Apollo-7B'] on worker 9e824afc ...
2024-06-15 10:29:50 | ERROR | stderr | Loading checkpoint shards:   0%|                          | 0/8 [00:00<?, ?it/s]
2024-06-15 10:29:50 | ERROR | stderr | Loading checkpoint shards:   0%|                          | 0/8 [00:00<?, ?it/s]
2024-06-15 10:29:50 | ERROR | stderr | 
2024-06-15 10:29:50 | ERROR | stderr | Traceback (most recent call last):
2024-06-15 10:29:50 | ERROR | stderr |   File "<frozen runpy>", line 198, in _run_module_as_main
2024-06-15 10:29:50 | ERROR | stderr |   File "<frozen runpy>", line 88, in _run_code
2024-06-15 10:29:50 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/model_worker.py", line 414, in <module>
2024-06-15 10:29:50 | ERROR | stderr |     args, worker = create_model_worker()
2024-06-15 10:29:50 | ERROR | stderr |                    ^^^^^^^^^^^^^^^^^^^^^
2024-06-15 10:29:50 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/model_worker.py", line 385, in create_model_worker
2024-06-15 10:29:50 | ERROR | stderr |     worker = ModelWorker(
2024-06-15 10:29:50 | ERROR | stderr |              ^^^^^^^^^^^^
2024-06-15 10:29:50 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/serve/model_worker.py", line 77, in __init__
2024-06-15 10:29:50 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2024-06-15 10:29:50 | ERROR | stderr |                                  ^^^^^^^^^^^
2024-06-15 10:29:50 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/model/model_adapter.py", line 362, in load_model
2024-06-15 10:29:50 | ERROR | stderr |     model, tokenizer = adapter.load_model(model_path, kwargs)
2024-06-15 10:29:50 | ERROR | stderr |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-15 10:29:50 | ERROR | stderr |   File "/home/c205/workspace/FastChat-main/fastchat/model/model_adapter.py", line 108, in load_model
2024-06-15 10:29:50 | ERROR | stderr |     model = AutoModelForCausalLM.from_pretrained(
2024-06-15 10:29:50 | ERROR | stderr |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-15 10:29:50 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 563, in from_pretrained
2024-06-15 10:29:50 | ERROR | stderr |     return model_class.from_pretrained(
2024-06-15 10:29:50 | ERROR | stderr |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-15 10:29:50 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3754, in from_pretrained
2024-06-15 10:29:50 | ERROR | stderr |     ) = cls._load_pretrained_model(
2024-06-15 10:29:50 | ERROR | stderr |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-06-15 10:29:50 | ERROR | stderr |   File "/home/c205/anaconda3/envs/fastchat/lib/python3.11/site-packages/transformers/modeling_utils.py", line 4237, in _load_pretrained_model
2024-06-15 10:29:50 | ERROR | stderr |     gc.collect()
2024-06-15 10:29:50 | ERROR | stderr | KeyboardInterrupt
